---
### [Change Name] ***
AWSTemplateFormatVersion: "2010-09-09"
Description: Create AWS IAM User etc.

Resources:
  ## IAM: Group
  GroupAdministrators:
    Type: AWS::IAM::Group
    Properties:
      GroupName: Administrators
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  ## IAM: User
  User***: ### [Change Name]
    Type: AWS::IAM::User
    Properties:
      UserName: *** ### [Change Name]
      LoginProfile:
        Password: 123456=NuFuA
        PasswordResetRequired: true
      Groups:
        - !Ref GroupAdministrators

Outputs:
  ## IAM: Group
  GroupAdministrators:
    Value: !GetAtt GroupAdministrators.Arn
    Export:
      Name: !Sub ${AWS::StackName}-GroupAdministrators

  ## IAM: User
  User***: ### [Change Name]
    Value: !GetAtt User***.Arn ### [Change Name]
    Export:
      Name: !Sub ${AWS::StackName}-User*** ### [Change Name]
