---
### [Change System Name] ***
### [Change Domain Name] ***.***
AWSTemplateFormatVersion: "2010-09-09"
Description: Create Route53 HostedZone

Parameters:
  SystemName:
    Description: System Name
    Type: String
    Default: *** ### [Change System Name]
  DomainName:
    Description: Domain name
    Type: String
    Default: ***.*** ### [Change Domain Name]
  Environment:
    Description: Environment
    Type: String
    Default: prod
    AllowedValues:
      - prod
      - stg
      - dev

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Environment Configuration"
        Parameters:
          - SystemName
          - DomainName
          - Environment

Conditions:
  isProd: !Equals [ !Ref Environment, prod ]

Resources:
  ## Hosted Zone
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !If [ isProd, !Ref DomainName, !Sub "${Environment}.${DomainName}" ]
      HostedZoneConfig:
        Comment: !Sub ${SystemName}-${Environment}-hostedzone
      HostedZoneTags:
        - Key: Name
          Value: !Sub ${SystemName}-${Environment}-hostedzone

  ## Record Set: CAA
  RecordSetCaa:
    Condition: isProd
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref DomainName
      Type: CAA
      ResourceRecords:
        - '0 issue "amazon.com"'
      TTL: 3600

Outputs:
  ## Hosted Zone
  HostedZone:
    Value: !Ref HostedZone
    Export:
      Name: !Sub ${AWS::StackName}-HostedZone

  HostedZoneDomainName:
    Value: !If [ isProd, !Ref DomainName, !Sub "${Environment}.${DomainName}" ]
    Export:
      Name: !Sub ${AWS::StackName}-HostedZoneDomainName

  HostedZoneNameServer1:
    Value: !Select [ 0, !GetAtt HostedZone.NameServers ]
    Export:
      Name: !Sub ${AWS::StackName}-HostedZoneNameServer1

  HostedZoneNameServer2:
    Value: !Select [ 1, !GetAtt HostedZone.NameServers ]
    Export:
      Name: !Sub ${AWS::StackName}-HostedZoneNameServer2

  HostedZoneNameServer3:
    Value: !Select [ 2, !GetAtt HostedZone.NameServers ]
    Export:
      Name: !Sub ${AWS::StackName}-HostedZoneNameServer3

  HostedZoneNameServer4:
    Value: !Select [ 3, !GetAtt HostedZone.NameServers ]
    Export:
      Name: !Sub ${AWS::StackName}-HostedZoneNameServer4

  ## Record Set: CAA
  RecordSetCaa:
    Condition: isProd
    Value: !Ref RecordSetCaa
    Export:
      Name: !Sub ${AWS::StackName}-RecordSetCaa
